merge_base_with = "origin/main"

[[linter]]
code = 'FLAKE8'
include_patterns = ['**/*.py']
exclude_patterns = [
    '.git/**',
    'backends/xnnpack/third-party/**',
    'build/**',
    'configurations/**',
    'docs/**',
    'tools/linter/adapters/**',
    'third_party/**',
    '**/*.pyi',
]
command = [
    'python3',
    'tools/linter/adapters/flake8_linter.py',
    '--',
    '@{{PATHSFILE}}'
]
init_command = [
    'python3',
    'tools/linter/adapters/pip_init.py',
    '--dry-run={{DRYRUN}}',
    'flake8==6.0.0',
    'flake8-bugbear==23.3.23',
    'flake8-comprehensions==3.12.0',
    'flake8-executable==2.1.3',
    'flake8-logging-format==0.9.0',
    'flake8-pyi==23.3.1',
    'flake8-simplify==0.19.3',
    'mccabe==0.7.0',
    'pycodestyle==2.10.0',
    'pyflakes==3.0.1',
]
is_formatter = true


[[linter]]
code = 'NEWLINE'
include_patterns=['**']
exclude_patterns=[
    'backends/xnnpack/third-party/**',
    'third_party/**',
    '**/*.bat',
    '**/*.expect',
    '**/*.ipynb',
    '**/*.ps1',
    '**/*.ptl',
    '**/*.png',
]
command = [
    'python3',
    'tools/linter/adapters/newlines_linter.py',
    '--',
    '@{{PATHSFILE}}',
]
is_formatter = true
